apiVersion: v1
kind: Service
metadata:
    name: nisha-3shapes-service
spec:
    selector:
       app: nisha-3shapes-app
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 8080
    type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
     name: nisha-3shapes-app
     labels:
        app: nisha-3shapes-app
spec:
   selector:
      matchLabels:
        app: nisha-3shapes-app
   replicas: 1
   template:
      metadata:
         labels:
            app: nisha-3shapes-app
      spec:
        containers:
          - name: nisha-3shapes-app
            image: 514924332194.dkr.ecr.eu-north-1.amazonaws.com/nisha3shapes:3_shapes
            imagePullPolicy: Always
            ports:
            - containerPort: 8080